apiVersion: v1
kind: Service
metadata:
  name: ms-b-service
  namespace: ms-b-ns
  labels:
    environment: production
    app: nginx
spec:
  selector:
    app: ms-b
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP