apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
  namespace: default
  labels:
    app: ms-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-a
      version: v1
  template:
    metadata:
      labels:
        app: ms-a
        version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-b
  namespace: ms-b-ns
  labels:
    app: ms-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-b
      version: v1
  template:
    metadata:
      labels:
        app: ms-b
        version: v1